### Cargar paquetes, definir setup y tema de gráficas ----
source("02_codigo/00_paquetes_setup_tema.R") 

### Función para cambiar y "limpiar" nombres de países y ciudades ----
limpiar_nombres_paises <- 
  function(bd) {
    bd %>%
      mutate(province_state = str_replace(province_state, ", AZ", ""),
             province_state = str_replace(province_state, ", CA", ""),
             province_state = str_replace(province_state, ", MA", ""),
             province_state = str_replace(province_state, ", WA", ""),
             province_state = str_replace(province_state, ", WI", ""),
             province_state = str_replace(province_state, ", IL", ""),
             province_state = str_replace(province_state, ", ON", ""),
             province_state = str_replace(province_state, "Taiwan", ""),
             province_state = str_replace(province_state, "Hong Kong", ""),
             province_state = str_replace(province_state, "British Columbia", "Columbia Británica"),
             province_state = str_replace(province_state, "Los Angeles", "Los Ángeles"),
             province_state = str_replace(province_state, "New South Wales", "Nueva Gales del Sur"),
             province_state = str_replace(province_state, "South Australia", "Australia del Sur"),
             province_state = str_replace(province_state, "Victoria", "Victoría"),
             province_state = str_replace(province_state, "Inner Mongolia", "Mongolia Interior"),
             province_state = str_replace(province_state, "Beijing", "Pekín"),
             province_state = ifelse(is.na(province_state), "", province_state),
             country_region = case_when(country_region == "Afghanistan" ~ "Afganistán",
                                        country_region == "Germany" ~ "Alemania",
                                        country_region == "Saudi Arabia" ~ "Arabia Saudita",
                                        country_region == "Algeria" ~ "Argelia",
                                        country_region == "Azerbaijan" ~ "Azerbaiyán",
                                        country_region == "Antigua and Barbuda" ~ "Antigua y Barbuda",
                                        country_region == "Bahamas, The" ~ "Bahamas",
                                        country_region == "The Bahamas" ~ "Bahamas",
                                        country_region == "Bahrain" ~ "Baréin",
                                        country_region == "Belgium" ~ "Bélgica",
                                        country_region == "Belize" ~ "Belice",
                                        country_region == "Belarus" ~ "Bielorrusia",
                                        country_region == "Bosnia and Herzegovina" ~ "Bosnia y Herzegovina",
                                        country_region == "Brazil" ~ "Brasil",
                                        country_region == "Bhutan" ~ "Bután",
                                        country_region == "Cape Verde" ~ "Cabo Verde",
                                        country_region == "Cambodia" ~ "Camboya",
                                        country_region == "Canada" ~ "Canadá",
                                        country_region == "Republic of Korea" ~ "Corea del Sur",
                                        country_region == "South Korea" ~ "Corea del Sur",
                                        country_region == "Korea, South" ~ "Corea del Sur",
                                        country_region == "Cote d'Ivoire" ~ "Costa de Marfil",
                                        country_region == "Mainland China" ~ "China",
                                        country_region == "Cyprus" ~ "Chipre",
                                        country_region == "Croatia" ~ "Croacia",
                                        country_region == "Denmark" ~ "Dinamarca",
                                        country_region == "United Arab Emirates" ~ "EAU",
                                        country_region == "US" ~ "EEUU",
                                        country_region == "Egypt" ~ "Egipto",
                                        country_region == "Spain" ~ "España",
                                        country_region == "Slovakia" ~ "Eslovaquia",
                                        country_region == "Slovenia" ~ "Eslovenia",
                                        country_region == "Eswatini" ~ "Esuatini",
                                        country_region == "Ethiopia" ~ "Etiopía",
                                        country_region == "Philippines" ~ "Filipinas",
                                        country_region == "Finland" ~ "Finlandia",
                                        country_region == "France" ~ "Francia",
                                        country_region == "Gabon" ~ "Gabón",
                                        country_region == "The Gambia" ~ "Gambia",
                                        country_region == "Gambia, The" ~ "Gambia",
                                        country_region == "West Bank and Gaza" ~ "Gaza",
                                        country_region == "Grenada" ~ "Granada",
                                        country_region == "Greece" ~ "Grecia",
                                        country_region == "Greenland" ~ "Groenlandia",
                                        country_region == "Guadeloupe" ~ "Guadalupe",
                                        country_region == "French Guiana" ~ "Guayana Francesa",
                                        country_region == "Fench Guiana" ~ "Guayana Francesa",
                                        country_region == "Guinea-Bissau" ~ "Guinea-Bisáu",
                                        country_region == "Equatorial Guinea" ~ "Guinea Ecuatorial",
                                        country_region == "Netherlands" ~ "Holanda",
                                        country_region == "Hong Kong" ~ "Hong Kong",
                                        country_region == "Hong Kong SAR" ~ "Hong Kong",
                                        country_region == "Hungary" ~ "Hungría",
                                        country_region == "Italy" ~ "Italia",
                                        country_region == "Iran" ~ "Irán",
                                        country_region == "Iran (Islamic Republic of)" ~ "Irán",
                                        country_region == "Republic of Ireland" ~ "Irlanda",
                                        country_region == "Ireland" ~ "Irlanda",
                                        country_region == "North Ireland" ~ "Irlanda del Norte",
                                        country_region == "Iceland" ~ "Islandia",
                                        country_region == "Cayman Islands" ~ "Islas Caimán",
                                        country_region == "St. Martin" ~ "Isla de San Martín",
                                        country_region == "Channel Islands" ~ "Islas del Canal",
                                        country_region == "Faroe Islands" ~ "Islas Faroe",
                                        country_region == "Japan" ~ "Japón",
                                        country_region == "Jordan" ~ "Jordania",
                                        country_region == "Kazakhstan" ~ "Kazajistán",
                                        country_region == "Kyrgyzstan" ~ "Kirguistán",
                                        country_region == "Latvia" ~ "Letonia",
                                        country_region == "Lebanon" ~ "Líbano",
                                        country_region == "Lithuania" ~ "Lituania",
                                        country_region == "Libya" ~ "Libia",
                                        country_region == "Luxembourg" ~ "Luxemburgo",
                                        country_region == "Macau" ~ "Macao",
                                        country_region == "Macao SAR" ~ "Macao",
                                        country_region == "North Macedonia" ~ "Macedonia del Norte",
                                        country_region == "Malaysia" ~ "Malasia",
                                        country_region == "Maldives" ~ "Maldivas",
                                        country_region == "Martinique" ~ "Martinica",
                                        country_region == "Mauritius" ~ "Mauricio",
                                        country_region == "Morocco" ~ "Marruecos",
                                        country_region == "Mexico" ~ "México",
                                        country_region == "Republic of Moldova" ~ "Moldovia",
                                        country_region == "Monaco" ~ "Mónaco",
                                        country_region == "Norway" ~ "Noruega",
                                        country_region == "New Zealand" ~ "Nueva Zelanda",
                                        country_region == "Oman" ~ "Omán",
                                        country_region == "Pakistan" ~ "Pakistán",
                                        country_region == "occupied Palestinian territory" ~ "Palestina",
                                        country_region == "Palestine" ~ "Palestina",
                                        country_region == "Papua New Guine" ~ "Papúa Nueva Guinea",
                                        country_region == "Papua New Guinea" ~ "Papúa Nueva Guinea",
                                        country_region == "Panama" ~ "Panamá",
                                        country_region == "Peru" ~ "Perú",
                                        country_region == "French Polynesia" ~ "Polinesia Francesa",
                                        country_region == "Poland" ~ "Polonia",
                                        country_region == "UK" ~ "Reino Unido",
                                        country_region == "United Kingdom" ~ "Reino Unido",
                                        country_region == "Cameroon" ~ "Camerún",
                                        country_region == "Central African Republic" ~ "Rep. Centroafricana",
                                        country_region == "Czechia" ~ "Rep. Checa",
                                        country_region == "Czech Republic" ~ "Rep. Checa",
                                        country_region == "Congo (Kinshasa)" ~ "Rep. Dem. del Congo",
                                        country_region == "Congo (Brazzaville)" ~ "Rep. del Congo",
                                        country_region == "Republic of the Congo" ~ "Rep. del Congo",
                                        country_region == "Dominican Republic" ~ "Rep. Dominicana",
                                        country_region == "Romania" ~ "Rumania",
                                        country_region == "Russia" ~ "Rusia",
                                        country_region == "Russian Federation" ~ "Rusia",
                                        country_region == "Rwanda" ~ "Ruanda",
                                        country_region == "Western Sahara" ~ "Sahara Occidental",
                                        country_region == "Saint Kitts and Nevis" ~ "San Cristóbal y Nieves",
                                        country_region == "Saint Vincent and the Grenadines" ~ "San Vincente y las Granadinas",
                                        country_region == "Saint Lucia" ~ "Santa Lucía",
                                        country_region == "Saint Barthelemy" ~ "San Bartolomé",
                                        country_region == "Saint Martin" ~ "Sint Maarten",
                                        country_region == "Sao Tome and Principe" ~ "Santo Tomé y Príncipe",
                                        country_region == "Singapore" ~ "Singapur",
                                        country_region == "South Africa" ~ "Sudáfrica",
                                        country_region == "Sudan" ~ "Sudán",
                                        country_region == "South Sudan" ~ "Sudán del Sur",
                                        country_region == "Sweden" ~ "Suecia",
                                        country_region == "Switzerland" ~ "Suiza",
                                        country_region == "Suriname" ~ "Surinam",
                                        country_region == "Syria" ~ "Siria",
                                        country_region == "Thailand" ~ "Tailandia",
                                        country_region == "Taiwan" ~ "Taiwán",
                                        country_region == "Taipei and environs" ~ "Taiwán",
                                        country_region == "Taiwan*" ~ "Taiwán",
                                        country_region == "Timor-Leste" ~ "Timor Oriental",
                                        country_region == "Trinidad and Tobago" ~ "Trinidad y Tobago",
                                        country_region == "Turkey" ~ "Turquía",
                                        country_region == "Tunisia" ~ "Túnez",
                                        country_region == "Holy See" ~ "Ciudad del Vaticano",
                                        country_region == "Vatican City" ~ "Ciudad del Vaticano",
                                        country_region == "Viet Nam" ~ "Vietnam",
                                        country_region == "Ukraine" ~ "Ucrania",
                                        country_region == "Uzbekistan" ~ "Uzbekistán",
                                        country_region == "Djibouti" ~ "Yibuti",
                                        country_region == "Zimbabwe" ~ "Zimbabue",
                                        country_region == "Diamond Princess" ~ "Crucero Diamond Princess",
                                        country_region == "MS Zaandam" ~ "Crucero MS Zaandam",
                                        country_region == "" ~ "",
                                        country_region == "" ~ "",
                                        country_region == "" ~ "",
                                        country_region == "" ~ "",
                                        TRUE ~ country_region),
             country_region = ifelse(province_state == "Diamond Princess cruise ship", "Crucero Diamond Princess", country_region),
             country_region = ifelse(province_state == "Diamond Princess", "Crucero Diamond Princess", country_region))
  }

